#ifndef VISUALISATIONCOLORS_HPP
#define VISUALISATIONCOLORS_HPP

#include <QColor>

#define COLOR_RED           QColor(255, 0, 0)
#define COLOR_NUMIX_ORANGE  QColor(214, 73, 55)
#define COLOR_ARCH_BLUE     QColor(23, 147, 209)
#define COLOR_NUMIX_GRAY    QColor(33, 33, 33)
#define COLOR_LIGHT_GRAY    QColor(116, 116, 116)
#define COLOR_DARK_PURPLE   QColor(42, 33, 64)
#define COLOR_TOXIC_GREEN   QColor(82, 240, 82)
#define COLOR_VIM_GREEN     QColor(85, 255, 85)
#define COLOR_BLUE_GREENISH QColor(1, 146, 151)

#define ITEM_EDGE_COLOR COLOR_BLUE_GREENISH
#define ITEM_NODE_COLOR COLOR_VIM_GREEN
#define ITEM_NODE_COLOR_CLICKED QColor(255, 0, 0)
#define ITEM_CIRCLE_COLOR COLOR_NUMIX_ORANGE
#define ITEM_BAD_TRIANGLE_COLOR QColor(255, 0, 0)
#define ITEM_SUPER_TRIANGLE_COLOR QColor(255, 255, 0)
#define ITEM_NODE_ACTIVE_COLOR COLOR_ARCH_BLUE

#endif // VISUALISATIONCOLORS_HPP
